//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponto_Eletronico.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.Funcionario_Cargo = new HashSet<Funcionario_Cargo>();
        }

        public Cargo(int id, string descricao)
        {
            this.Id = id;
            this.Descricao = descricao;
        }

        public Cargo(string descricao)
        {
            this.Descricao = descricao;
        }

        [Key]
        public int Id { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Digite a Descrição do Cargo.")]
        [MinLength(2, ErrorMessage = "O tamanho mínimo da descrição são 2 caracteres.")]
        [StringLength(50, ErrorMessage = "O tamanho máximo da descrição são 50 caracteres.")]
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario_Cargo> Funcionario_Cargo { get; set; }
    }
}
