//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponto_Eletronico.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    public partial class Ponto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Ponto() { }

        //public Ponto(int id, int id_Funcionario, DateTime data_hora_entrada, DateTime data_hora_saida)
        //{
        //    this.Id = id;
        //    this.id_Funcionario = id_Funcionario;
        //    this.data_hora_entrada = data_hora_entrada;
        //    this.data_hora_saida = data_hora_saida;
        //}

        [Key]
        public int Id { get; set; }

        [Column(Order = 0)]
        [Display(Name = "Funcionário")]
        public int id_Funcionario { get; set; }

        [Column(Order = 1)]
        [DataType(DataType.DateTime)]
        [Display(Name = "Data Hora Entrada")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public System.DateTime data_hora_entrada { get; set; }

        [Column(Order = 2)]
        [DataType(DataType.DateTime)]
        [Display(Name = "Data Hora Saída")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> data_hora_saida { get; set; }

        public virtual Funcionario Funcionario { get; set; }
    }
}
